spring.application.name=api-gateway

server.port=8080

# Gateway Routes
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**

# Actuator
management.endpoints.web.exposure.include=health,info,gateway