apiVersion: v2
name: order-management-system
description: A Helm chart for Order Management System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservices
  - spring-boot
  - kubernetes
  - kafka
  - postgresql
maintainers:
  - name: Ruben
sources:
  - https://github.com/tu-usuario/order-management-system
